name: build-pocolibs
on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    types:
    - opened
    - reopened
    - unlabeled
    paths:
      - '**/pocolibs/.ci_support/*.yaml'

jobs:
  check-depends-on-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Fail in case Pull Request is opened with label "depends-on"
        if: ${{ contains(github.event.pull_request.labels.*.name, 'depends-on') }}
        run: |
          echo "Pull Request was open with a depends-on label and is blocked."
          echo "Merge listed PRs in comment first and unlabel this PR."
          exit 1

      - name: Succeed otherwise
        if: ${{ !contains(github.event.pull_request.labels.*.name, 'depends-on') }}
        run: |
          echo "Pull Request was not opened with a depends-on label, continuing..."

  build-pocolibs-sofa:
    strategy:
      fail-fast: false
      matrix:
        target: [{platform: "linux-64", runner: "ubuntu-latest"},
                 {platform: "linux-aarch64", runner: "ubuntu-24.04-arm"},
                 {platform: "osx-64", runner: "macos-15-intel"},
                 {platform: "osx-arm64", runner: "macos-latest"}]

    uses: ./.github/workflows/build_publish_package.yml
    needs: check-depends-on-PR
    with:
      package-name: pocolibs
      runner: ${{ matrix.target.runner }}
      platform: ${{ matrix.target.platform }}
      channel: telekyb-forge
    secrets:
      api-key: ${{ secrets.PREFIX_DEV_API_KEY }}